CREATE TABLE "biodome" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"bundle"	TEXT NOT NULL UNIQUE,
	"version"	INTEGER NOT NULL DEFAULT (0)
);
CREATE TABLE "item" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"bundle"	TEXT NOT NULL UNIQUE,
	"version"	INTEGER NOT NULL DEFAULT (0)
);